### ISSUE TITLE
apply for maintainer for POCO X3 PRO

### ISSUE THREAD

**Issue by clhexftw** [CipherOS/maintainership#2]
## Device
Your device codename : vayu
Your device name: POCO X3 PRO
Your device brand: Xiaomi

## Trees

https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher
https://github.com/clhexvayulab/kernel_xiaomi_vayu
https://github.com/clhexvayulab/android_vendor_xiaomi_vayu

## Source patches
None

## Any bugs
No

## Unofficial POST LINK

device specific channel:
a12L: https://t.me/PocoX3ProIndonesiaUpdate/1808
a12: https://t.me/PocoX3ProIndonesiaUpdate/1802

my channel:
a12L: https://t.me/clhex_blog/76
a12: https://t.me/clhex_blog/75

## Usernames
Your Telegram username: clhexftw
Your GitHub username: clhexftw
Your Sourceforge username: clhexftw

## Extra
On device specific channel only indo channel posted not the global one because global admin was busy

**Comment by alibei** [comment]
Rejected

You could squash these two together:
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/f423e6320c813895451a1d0b1cb2e1ee0e2be7d9
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/758033c121dceca6f252c61b4c0d76212b171072

Makes no sense, msmnile even supports armv8-2a-dotprod:
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/8a3c909b104afe4015a4dab60374440369a12a41

Wrong location and we don't have this:
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/328a5ef84234da901d4e4040eb8ad880e47387b1

You pushed a complete system.prop but your commit states it's for opencamera
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/449256a3d0fa8c1388ac7dd01f4394b26369e3c0

You can re-apply next month
