### ISSUE TITLE
RMX2061: Realme 6 Pro

### ISSUE THREAD

**Issue by neel0210** [CipherOS/maintainership#3]
## Device
```
RMX2061
Realme 6 Pro
Realme
```

## Trees
```
https://github.com/Realme-6-pro/device_realme_RXM2061
https://github.com/Realme-6-pro/vendor_realme
https://github.com/Realme-6-pro/vendor_realme
```

## Source patches
```
None
```

## Any bugs
```
No
```

## Unofficial
```
https://t.me/neelsdevelopment/495
```

## Usernames
```
https://t.me/neel0210
https://forum.xda-developers.com/m/neel0210.9821139/
https://sourceforge.net/u/neel0210/profile
https://github.com/neel0210
```

## Extra
```
No
```

**Comment by alibei** [comment]
Rejected

Where is the kernel source you use?

Why this? Our gapps is already debloated or at least adapt to our gapps
https://github.com/Realme-6-pro/device_realme_RXM2061/commit/36543191c8f3c0ce17ab172e861f758f9741e140
https://github.com/Realme-6-pro/device_realme_RXM2061/commit/210bc36107c10718f0ac9e1defa05904a259582e

Why two commits for fp?
https://github.com/Realme-6-pro/device_realme_RXM2061/commit/37fc82c25291320c3960b4c55845c2af4651b17f
https://github.com/Realme-6-pro/device_realme_RXM2061/commit/b2392662164273e974c2c79a49797550767fcc39

These two commits should be one
https://github.com/Realme-6-pro/device_realme_RXM2061/commit/183a160cec30d3ee472b7f6754dc84d7b6ee3480
https://github.com/Realme-6-pro/device_realme_RXM2061/commit/b313357f6fb270e665da72fb1ed5d47d57a4bdfb

Then it is just a bringup and we want people to work on their trees
