### ISSUE TITLE
Maintainership req for x3p

### ISSUE THREAD

**Issue by clhexftw** [CipherOS/maintainership#5]
## Device
```
Your device codename: vayu/bhima
Your device name: POCO X3 PRO
Your device brand: Xiaomi
```

## Trees

```
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher
https://github.com/clhexvayulab/android_kernel_xiaomi_vayu
https://github.com/clhexvayulab/android_vendor_xiaomi_vayu
```

## Source patches

```
None
```

## Any bugs

```
No
```

## Unofficial

```
a12L: https://t.me/PocoX3ProIndonesiaUpdate/1808
a12: https://t.me/PocoX3ProIndonesiaUpdate/1802
```

## Usernames

```
Your Telegram username: clhexftw
Your GitHub username : clhexftw
Your Sourceforge username: clhexftw
```

## Extra

```
No
```

**Comment by alibei** [comment]
Hi,

why this in the bringup commit and why you changed that back?
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/9495b5adb2b1f694fd6e300d16846f23bb7ab533#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5L15

there is a conflict
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/333b0c5c5985b42d561a85b751b0aab983355d32#diff-7878e0b94a80b96d7f4e0b1bc4702fcf4127c2c8b1942ac49048e4bb190b1263R90
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/adfbd83b7fc7dbf253a1d5668e118931c3a9a389#diff-ec61e57fc1916a9f4ec029d3b00d8b23020339427da76526c1442ba06a70cfc5R16

this is an extra commit and should not be squashed
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/e76423c178c6bb3190b6bd5358d0576cd47e5edb#diff-a71c801667070153aeee0e031b8502035e714083a8f17d5770e1d2acc6f51a8bR673

did you check if iorapd works?
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/70787d1fad9377e99abf1f1bc89d9d1e8f0b369e

this does not exist in clhexvayulab
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/blob/99e5a3a23579cc18f05f01c8c65a9f570e550b9a/cipher.dependencies#L11

branches you use for cipher should be named to twelve-L

**Comment by clhexftw** [comment]
hi 
https://github.com/ArrowOS-Devices/android_packages_apps_GCamGOPrebuilt
this is where i m tracking 

> Hi,
> 
> why this in the bringup commit and why you changed that back? [clhexvayulab/android_device_xiaomi_vayu-cipher@9495b5a#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5L15](https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/9495b5adb2b1f694fd6e300d16846f23bb7ab533#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5L15)
> 
> there is a conflict [clhexvayulab/android_device_xiaomi_vayu-cipher@333b0c5#diff-7878e0b94a80b96d7f4e0b1bc4702fcf4127c2c8b1942ac49048e4bb190b1263R90](https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/333b0c5c5985b42d561a85b751b0aab983355d32#diff-7878e0b94a80b96d7f4e0b1bc4702fcf4127c2c8b1942ac49048e4bb190b1263R90) [clhexvayulab/android_device_xiaomi_vayu-cipher@adfbd83#diff-ec61e57fc1916a9f4ec029d3b00d8b23020339427da76526c1442ba06a70cfc5R16](https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/adfbd83b7fc7dbf253a1d5668e118931c3a9a389#diff-ec61e57fc1916a9f4ec029d3b00d8b23020339427da76526c1442ba06a70cfc5R16)
> 
> this is an extra commit and should not be squashed [clhexvayulab/android_device_xiaomi_vayu-cipher@e76423c#diff-a71c801667070153aeee0e031b8502035e714083a8f17d5770e1d2acc6f51a8bR673](https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/e76423c178c6bb3190b6bd5358d0576cd47e5edb#diff-a71c801667070153aeee0e031b8502035e714083a8f17d5770e1d2acc6f51a8bR673)
> 
> did you check if iorapd works? [clhexvayulab/android_device_xiaomi_vayu-cipher@70787d1](https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/70787d1fad9377e99abf1f1bc89d9d1e8f0b369e)
> 
> this does not exist in clhexvayulab https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/blob/99e5a3a23579cc18f05f01c8c65a9f570e550b9a/cipher.dependencies#L11
> 
> branches you use for cipher should be named to twelve-L

Hello https://github.com/ArrowOS-Devices/android_packages_apps_GCamGOPrebuilt here is the repo i m getting this from i git clone this directly in my server : https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/blob/99e5a3a23579cc18f05f01c8c65a9f570e550b9a/cipher.dependencies#L11

and sorry about conflict i was little busy so i that didnt got my attention i will fix it for sure sir

and about iorapd i will simply revert it if it didnt worked in my test builds

**Comment by alibei** [comment]
Hi, fix your commits

**Comment by clhexftw** [comment]
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/branches

**Comment by clhexftw** [comment]
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/aa1bd1f1f5fd0c5cab84c241b77b0e2426ce8fe3 
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/67874786ad8972998eb57becad5ce0f6ee3686f5
Fixed these picks and also renamed branch name to twelve-L as u told

**Comment by clhexftw** [comment]
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/f8a3d49e5f23f91e3a8f4bfefa8f0cde0b374ca2
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/67874786ad8972998eb57becad5ce0f6ee3686f5
Fixed that cherrypick thanks ! for telling me abt that xD

**Comment by alibei** [comment]
Just tell us when you fixed everything and tested iorapd (I want to see the test result)

**Comment by clhexftw** [comment]
https://github.com/ArrowOS-Devices/android_device_xiaomi_vayu/commits now fine ig

**Comment by alibei** [comment]
Still in the bringup commit
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/9495b5adb2b1f694fd6e300d16846f23bb7ab533#diff-151aef4e286613b79b65e512509f8c5b43c20939baff4c9e65e38ab639e0e7a5L15

Still a conflict
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/333b0c5c5985b42d561a85b751b0aab983355d32#diff-7878e0b94a80b96d7f4e0b1bc4702fcf4127c2c8b1942ac49048e4bb190b1263R90

Where is the test result?
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/a63f0743b974c547ee9865abe7e9cb810a130241

You nuked gcamgo but some apps need a default camera (for example snap)
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/8a59c87d3a724f27427d18bebebd688b7c08d479#diff-247ee86229a709a6e2eedfc1d3c4a557825aee073e20b0112ab76f4ca8e4bc4eL103

Like I said that should be an extra commit
https://github.com/clhexvayulab/android_device_xiaomi_vayu-cipher/commit/a13d97c201fe881e619190c68ec6d7202ef76c94#diff-a71c801667070153aeee0e031b8502035e714083a8f17d5770e1d2acc6f51a8bL676

Declined. You can re-apply next month
