### ISSUE TITLE
new maintainer (vayu)

### ISSUE THREAD

**Issue by daltion369** [CipherOS/maintainership#6]
## Device
```
Your device codename : vayu/bhima
Your device name: Poco X3 pro
Your device brand: Xiaomi
```

## Trees

```
https://github.com/daltion369/android_device_xiaomi_vayu
https://github.com/daltion369/android_kernel_xiaomi_vayu
https://github.com/daltion369/android_vendor_xiaomi_vayu
```

## Source patches

```
None
```

## Any bugs

```
No
```

## Unofficial

```
https://t.me/PocoX3ProUpdates/1135
```

## Usernames

```
Your Telegram username: dlt_369
Your GitHub username: daltion369
Your XDA username
Your Sourceforge username
```

## Extra

```
Ignore safetynet fails in post now its fixed
```

**Comment by rain2wood** [comment]
https://github.com/daltion369/android_device_xiaomi_vayu/commit/045d33551bc92371f511d3433fd72abdab129418
We already have this in vendor (https://github.com/CipherOS/android_vendor_cipher/commit/4b06799871bf707d227f15b122d29902cee5f5d8).

https://github.com/daltion369/android_device_xiaomi_vayu/commit/48cb6aab6d94088dda67ab1f401280c6cf6aea7c
CipherOS does not have this flag.

https://github.com/daltion369/android_device_xiaomi_vayu/commit/d3795f9f67d32c0744c22c1a397fe92e026ddc05
Why? We don't ship Open Camera by default,.

Also, a side note:
It seems weird to me when you enable Smooth Display option in Settings while adding a Refresh rate QS Tile.

**Comment by daltion369** [comment]
1. ok i have nuked that prop and pushed
2. i thought cipher have it almost every roms have that so nuked btw
3.  On adding support for aux camera in open camera it adds support for for switching lenses not something big though but i use it personally sometimes that why i picked

**Comment by daltion369** [comment]
> > * ok i have nuked that prop and pushed
> > * i thought cipher have it almost every roms have that so nuked btw
> > * On adding support for aux camera in open camera it adds support for switching lenses not something big though but i use it personally opencam sometimes thats
> >   why i picked
> 
> Replying to 3, if you "personally" use it then please keep your changes "personal". You can add that prop in build.prop yourself, you don't have to do it to all users.
> 
> Also, does Smooth Display option in settings conflict with Refresh Rate tile?

ok i have nuked that aux cam commit and about refresh rate tile no it have 0 conflicts with smooth display if u turn on smooth display i will be 120hz no matter if refresh tile have 30 or 90 selected

**Comment by alibei** [comment]
This is not needed as SafetyNet get bypassed automatically by PixelPropsUtils

**Comment by daltion369** [comment]
> This is not needed as SafetyNet get bypassed automatically by PixelPropsUtils [daltion369/android_device_xiaomi_vayu@99febba](https://github.com/daltion369/android_device_xiaomi_vayu/commit/99febba7118d0d57c35ce29482021f00fe98289f)

oh okie fixed

**Comment by techyminati** [comment]
You're accepted, Drop a mail to us on cipher.rom@gmail.com and we'll send invite links to Maintainer Chat.
