### ISSUE TITLE
new maintainer (flashlmdd)

### ISSUE THREAD

**Issue by anht3889** [CipherOS/maintainership#7]
## Device
```
Your device codename: flahsmdd
Your device name: LG V50 ThinQ
Your device brand: LG
```

## Trees

```
https://github.com/anht3889/device_lge_sm8150-common
https://github.com/anht3889/device_lge_flashlmdd
https://github.com/anht3889/device_lge_flash-common
https://github.com/anht3889/device_lge_common
```

## Source patches

```
None
```

## Any bugs

```
No
```

## Unofficial

```
https://t.me/v50thinq/387731
```

## Usernames

```
Your Telegram username: anht3889
Your GitHub username: anht3889
Your XDA username: quantan
```

## Extra

```
No
```

**Comment by techyminati** [comment]
> ## Device
> ```
> Your device codename: flahsmdd
> Your device name: LG V50 ThinQ
> Your device brand: LG
> ```
> 
> ## Trees
> ```
> https://github.com/anht3889/device_lge_sm8150-common
> https://github.com/anht3889/device_lge_flashlmdd
> https://github.com/anht3889/device_lge_flash-common
> https://github.com/anht3889/device_lge_common
> ```
> 
> ## Source patches
> ```
> None
> ```
> 
> ## Any bugs
> ```
> No
> ```
> 
> ## Unofficial
> ```
> https://t.me/v50thinq/387731
> ```
> 
> ## Usernames
> ```
> Your Telegram username: anht3889
> Your GitHub username: anht3889
> Your XDA username: quantan
> ```
> 
> ## Extra
> ```
> No
> ```

Why did you link ricedroid as "unofficial" build?

**Comment by anht3889** [comment]
> Why did you link ricedroid as "unofficial" build?

Actually at that time I didn't have access to their github org so I considered it as an unofficial build. Here are some my recent unofficial build: https://t.me/v50thinq/411246

**Comment by alibei** [comment]
You did not read our requirements for official. Also you did not compile and release any cipher build.
